### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by stephane-daviet-maif** [Download/picolog#4]
I would like to know if you still maintain your library. I see latest commit is 4 years old, but it can also means that there is nothing to change and that the library is just perfect as is  :wink:.

**Comment by Download** [comment]
Ha ha well I would not call it perfect but it works.

I recommend you look at [`ulog`](https://npmjs.com/package/ulog), the successor to picolog. I have been writing logging code for a long time and changing it, because it is something that comes back in all my projects. Picolog was one of the first libraries I wrote. When I was trying to create a next version for it, a friendly fellow programmer gave me the package name `ulog` which I liked more. So it truly is the next version of Picolog.

**Comment by stephane-daviet-maif** [comment]
Thanks for your answer and for the link to ulog. As a first library, it's quite a well done one.
